// POST /api/reports/weekly/notion
// Exports the current week's delivery report to Notion.
//
// Required env vars:
//   NOTION_TOKEN            — internal integration token (starts "secret_…")
//   NOTION_REPORTS_PAGE_ID  — ID of the Notion page to create the report under
//
// Setup (5 min):
//   1. notion.so/my-integrations → New integration → name "DeliveryOps"
//      → Internal → copy the "Internal Integration Token"
//   2. Open the Notion page where reports should land → ⋯ → Add connections
//      → DeliveryOps → paste the page ID from the URL
//      (https://notion.so/{workspace}/{PAGE_ID}?...)
//   3. Add both vars to .env.local and Vercel
//
// Response:
//   { url: string }  — the Notion URL of the created page, opened client-side

import { NextResponse } from "next/server";
import { loadWeeklyBundle } from "@/lib/reports/weekly-loader";

export const dynamic = "force-dynamic";
export const maxDuration = 30;

const NOTION_TOKEN    = process.env.NOTION_TOKEN;
const PARENT_PAGE_ID  = process.env.NOTION_REPORTS_PAGE_ID;

export async function POST() {
  // If token not set yet, return 501 so the client shows the "Connect Notion" message.
  if (!NOTION_TOKEN || !PARENT_PAGE_ID) {
    return NextResponse.json({ error: "Notion not configured." }, { status: 501 });
  }

  const bundle = await loadWeeklyBundle();

  // Build Notion blocks.
  const blocks: NotionBlock[] = [
    heading2(`📦 Shipped this week (${bundle.totals.shipped_this_week})`),
    ...( bundle.shipped_this_week.length === 0
      ? [paragraph("No projects went live this week.")]
      : bundle.shipped_this_week.map((p) =>
          bulletedListItem(`${p.customer_display_name} — ${p.name}${p.ttv_days ? ` · ${p.ttv_days}d TTV` : ""}`)
        )
    ),

    divider(),

    heading2(`🚀 Upcoming go-lives — next 14 days (${bundle.totals.upcoming_14d})`),
    ...( bundle.upcoming_14d.length === 0
      ? [paragraph("No projects scheduled in the next 14 days.")]
      : bundle.upcoming_14d.map((p) =>
          bulletedListItem(`${p.customer_display_name} — ${p.name} · ${fmtDate(p.go_live_date)} (${p.days_until_live}d away)`)
        )
    ),

    divider(),

    heading2(`⚡ In flight (${bundle.totals.in_flight})`),
    ...( bundle.in_flight.length === 0
      ? [paragraph("No active projects.")]
      : bundle.in_flight.slice(0, 20).map((p) =>
          bulletedListItem(`${p.customer_display_name} — ${p.name}${p.health ? ` [${p.health}]` : ""}`)
        )
    ),
    ...(bundle.in_flight.length > 20
      ? [paragraph(`… and ${bundle.in_flight.length - 20} more`)]
      : []
    ),

    divider(),

    heading2(`⚠️ At risk (${bundle.totals.at_risk})`),
    ...( bundle.at_risk.length === 0
      ? [paragraph("✅ All clear — no at-risk projects.")]
      : bundle.at_risk.map((p) =>
          bulletedListItem(`${p.customer_display_name} — ${p.name}${p.health ? ` [${p.health}]` : ""}${p.latest_update ? `\n${p.latest_update}` : ""}`)
        )
    ),

    divider(),

    heading2("📊 Team workload (active projects)"),
    ...( bundle.workload_tam.slice(0, 10).map((r) =>
        bulletedListItem(`TAM: ${r.person} — ${r.active} active`)
    )),
    ...( bundle.workload_dev.slice(0, 10).map((r) =>
        bulletedListItem(`Dev: ${r.person} — ${r.active} active`)
    )),

    ...( bundle.nps_this_quarter ? [
      divider(),
      heading2(`💬 NPS this quarter: ${bundle.nps_this_quarter.average > 0 ? "+" : ""}${bundle.nps_this_quarter.average}`),
      paragraph(`${bundle.nps_this_quarter.count} response${bundle.nps_this_quarter.count !== 1 ? "s" : ""} · ${bundle.nps_this_quarter.quarter}`),
    ] : []),

    divider(),
    paragraph(`Generated by DeliveryOps · ${new Date(bundle.generated_at).toLocaleString("en-US", { dateStyle: "full", timeStyle: "short" })}`),
  ];

  // Create the Notion page.
  const res = await fetch("https://api.notion.com/v1/pages", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${NOTION_TOKEN}`,
      "Content-Type": "application/json",
      "Notion-Version": "2022-06-28",
    },
    body: JSON.stringify({
      parent: { page_id: PARENT_PAGE_ID },
      icon: { type: "emoji", emoji: "📋" },
      properties: {
        title: {
          title: [{ type: "text", text: { content: `Weekly Delivery Update · ${bundle.week_label}` } }],
        },
      },
      children: blocks,
    }),
  });

  if (!res.ok) {
    const err = await res.text();
    console.error("[notion] page create failed:", err);
    return NextResponse.json({ error: "Notion API error." }, { status: 502 });
  }

  const page = (await res.json()) as { url: string };
  return NextResponse.json({ url: page.url });
}

// ── Block builders ────────────────────────────────────────────────────────────
interface NotionBlock { object: "block"; type: string; [k: string]: unknown }

function richText(content: string) {
  return [{ type: "text", text: { content } }];
}

function heading2(content: string): NotionBlock {
  return { object: "block", type: "heading_2", heading_2: { rich_text: richText(content) } };
}

function paragraph(content: string): NotionBlock {
  return { object: "block", type: "paragraph", paragraph: { rich_text: richText(content) } };
}

function bulletedListItem(content: string): NotionBlock {
  return { object: "block", type: "bulleted_list_item", bulleted_list_item: { rich_text: richText(content) } };
}

function divider(): NotionBlock {
  return { object: "block", type: "divider", divider: {} };
}

function fmtDate(iso: string | null): string {
  if (!iso) return "—";
  return new Date(iso).toLocaleDateString("en-US", { month: "short", day: "numeric", timeZone: "UTC" });
}
