"use client";

import { useState, useRef, useEffect } from "react";
import {
  BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip,
  ResponsiveContainer, Cell, ReferenceLine,
} from "recharts";
import { useTheme } from "next-themes";
import type { WeeklyBundle, WeeklyProject } from "@/lib/reports/weekly-loader";

// ── Chart theme ───────────────────────────────────────────────────────────────
function useChartTheme() {
  const { resolvedTheme } = useTheme();
  const [mounted, setMounted] = useState(false);
  useEffect(() => setMounted(true), []);
  const dark = mounted && resolvedTheme === "dark";
  return {
    grid: dark ? "rgba(255,255,255,0.05)" : "rgba(0,0,0,0.05)",
    axis: dark ? "#71717a" : "#a1a1aa",
    tooltipStyle: {
      background: dark ? "#18181b" : "#ffffff",
      border: dark ? "1px solid rgba(255,255,255,0.1)" : "1px solid rgba(0,0,0,0.08)",
      borderRadius: 10, padding: "8px 12px", fontSize: 12,
    },
  };
}

// ── Helpers ───────────────────────────────────────────────────────────────────
function fmtDate(iso: string | null): string {
  if (!iso) return "—";
  return new Date(iso).toLocaleDateString("en-US", { month: "short", day: "numeric", timeZone: "UTC" });
}
function timeAgo(iso: string | null): string {
  if (!iso) return "never";
  const ms = Date.now() - new Date(iso).getTime();
  if (ms < 3_600_000) return `${Math.round(ms / 60_000)}m ago`;
  if (ms < 86_400_000) return `${Math.round(ms / 3_600_000)}h ago`;
  return `${Math.round(ms / 86_400_000)}d ago`;
}

const HEALTH_PILL: Record<string, string> = {
  "On Track": "bg-emerald-500/12 text-emerald-700 dark:text-emerald-400 border-emerald-500/25",
  Healthy:    "bg-emerald-500/12 text-emerald-700 dark:text-emerald-400 border-emerald-500/25",
  "At Risk":  "bg-red-500/12 text-red-700 dark:text-red-400 border-red-500/25",
  "Off Track":"bg-red-500/12 text-red-700 dark:text-red-400 border-red-500/25",
  Stuck:      "bg-red-500/12 text-red-700 dark:text-red-400 border-red-500/25",
};
function HealthPill({ health }: { health: string | null }) {
  if (!health) return null;
  const cls = HEALTH_PILL[health] ?? "bg-zinc-500/12 text-zinc-600 dark:text-zinc-400 border-zinc-500/25";
  return <span className={`text-[10px] px-1.5 py-0.5 rounded border font-medium ${cls}`}>{health}</span>;
}

// ── Export helpers ────────────────────────────────────────────────────────────
function buildMarkdown(bundle: WeeklyBundle): string {
  const lines: string[] = [];
  const L = (s: string) => lines.push(s);

  L(`# Weekly Delivery Update`);
  L(`**${bundle.week_label}**  ·  Generated by DeliveryOps`);
  L(``);

  // Hero numbers
  L(`## At a glance`);
  L(`| Metric | Count |`);
  L(`|---|---|`);
  L(`| Shipped last week | ${bundle.totals.shipped_last_week} |`);
  L(`| In flight (active) | ${bundle.totals.in_flight} |`);
  L(`| In UAT | ${bundle.totals.in_uat} |`);
  L(`| At risk | ${bundle.totals.at_risk} |`);
  L(`| Delivered all time | ${bundle.totals.delivered_all_time} |`);
  L(``);

  // Phase breakdown
  L(`## Active projects by phase`);
  L(`| Phase | Count |`);
  L(`|---|---|`);
  L(`| Discovery | ${bundle.by_phase.discovery} |`);
  L(`| Development | ${bundle.by_phase.dev} |`);
  L(`| UAT | ${bundle.by_phase.uat} |`);
  L(`| Other | ${bundle.by_phase.other} |`);
  L(``);

  // Shipped
  L(`## Shipped last week (${bundle.shipped_last_week.length})`);
  if (!bundle.shipped_last_week.length) {
    L(`_No projects went live last week._`);
  } else {
    for (const p of bundle.shipped_last_week) {
      L(`- **${p.customer_display_name}** — ${p.name}${p.ttv_days ? ` · ${p.ttv_days}d TTV` : ""}${p.go_live_date ? ` · went live ${fmtDate(p.go_live_date)}` : ""}`);
    }
  }
  L(``);

  // UAT
  L(`## In UAT — ready for sign-off (${bundle.in_uat.length})`);
  if (!bundle.in_uat.length) {
    L(`_No projects currently in UAT._`);
  } else {
    for (const p of bundle.in_uat) {
      L(`- **${p.customer_display_name}** — ${p.name}${p.phase ? ` [${p.phase}]` : ""}`);
    }
  }
  L(``);

  // At risk
  L(`## At risk (${bundle.at_risk.length})`);
  if (!bundle.at_risk.length) {
    L(`✅ All clear — no at-risk projects.`);
  } else {
    for (const p of bundle.at_risk) {
      L(`- **${p.customer_display_name}** — ${p.name} [${p.health ?? "?"}]`);
      if (p.latest_update) L(`  > ${p.latest_update}`);
    }
  }
  L(``);

  // In flight
  L(`## In flight (${bundle.totals.in_flight})`);
  for (const p of bundle.in_flight) {
    L(`- ${p.customer_display_name} — ${p.name}${p.phase ? ` [${p.phase}]` : ""}${p.health ? ` · ${p.health}` : ""}`);
  }
  L(``);

  // In production
  L(`## In production`);
  L(`| Metric | Count |`);
  L(`|---|---|`);
  L(`| Total delivered (all time) | ${bundle.in_prod.projects} |`);
  L(`| Customers with live automations | ${bundle.in_prod.customers} |`);
  L(`| Delivered this quarter | ${bundle.in_prod.this_quarter} |`);
  L(`| Delivered last quarter | ${bundle.in_prod.last_quarter} |`);
  L(``);

  // Team workload
  if (bundle.workload_tam.length > 0) {
    L(`## Team workload — TAM / CSM`);
    for (const r of bundle.workload_tam) L(`- ${r.person}: ${r.active} active`);
    L(``);
  }
  if (bundle.workload_dev.length > 0) {
    L(`## Team workload — Engineering / SE`);
    for (const r of bundle.workload_dev) L(`- ${r.person}: ${r.active} active`);
    L(``);
  }

  if (bundle.nps_this_quarter) {
    L(`## NPS this quarter`);
    L(`**${bundle.nps_this_quarter.average > 0 ? "+" : ""}${bundle.nps_this_quarter.average}** · ${bundle.nps_this_quarter.count} responses · ${bundle.nps_this_quarter.quarter}`);
    L(``);
  }

  L(`---`);
  L(`_DeliveryOps · data from Monday.com · synced ${timeAgo(bundle.last_sync)}_`);
  return lines.join("\n");
}

// ── Export buttons ────────────────────────────────────────────────────────────
function ExportButtons({ bundle, reportRef }: { bundle: WeeklyBundle; reportRef: React.RefObject<HTMLDivElement | null> }) {
  const [mdState, setMdState] = useState<"idle" | "copied" | "error">("idle");
  const [pngState, setPngState] = useState<"idle" | "loading" | "done" | "error">("idle");

  async function copyMarkdown() {
    try {
      await navigator.clipboard.writeText(buildMarkdown(bundle));
      setMdState("copied");
      setTimeout(() => setMdState("idle"), 2500);
    } catch {
      setMdState("error");
      setTimeout(() => setMdState("idle"), 2500);
    }
  }

  async function downloadPng() {
    setPngState("loading");
    try {
      // Lazy-load html2canvas only when user clicks — keeps initial bundle small.
      const html2canvas = (await import("html2canvas")).default;
      const el = reportRef.current;
      if (!el) throw new Error("No report element");
      const canvas = await html2canvas(el, {
        backgroundColor: null,
        scale: 2,
        useCORS: true,
        logging: false,
        // Ignore the export button strip itself so it doesn't appear in the image.
        ignoreElements: (el) => el.id === "export-strip",
      });
      const url = canvas.toDataURL("image/png");
      const a = document.createElement("a");
      a.href = url;
      a.download = `deliveryops-weekly-${bundle.week_label.replace(/[^a-z0-9]/gi, "-").toLowerCase()}.png`;
      a.click();
      setPngState("done");
      setTimeout(() => setPngState("idle"), 2500);
    } catch {
      setPngState("error");
      setTimeout(() => setPngState("idle"), 2500);
    }
  }

  const mdLabel = mdState === "copied" ? "Copied ✓" : mdState === "error" ? "Failed" : "Copy as Markdown";
  const pngLabel = pngState === "loading" ? "Rendering…" : pngState === "done" ? "Saved ✓" : pngState === "error" ? "Failed" : "Download PNG";

  return (
    <div id="export-strip" className="flex items-center gap-2 flex-wrap">
      <button
        onClick={copyMarkdown}
        className="inline-flex items-center gap-1.5 rounded-xl border border-[var(--glass-border)] px-3.5 py-2 text-sm font-medium text-[color:var(--foreground)] hover:bg-[rgba(0,0,0,0.04)] dark:hover:bg-[rgba(255,255,255,0.04)] transition-colors"
      >
        <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="9" y="9" width="13" height="13" rx="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg>
        {mdLabel}
      </button>
      <button
        onClick={downloadPng}
        disabled={pngState === "loading"}
        className="inline-flex items-center gap-1.5 rounded-xl border border-[var(--glass-border)] px-3.5 py-2 text-sm font-medium text-[color:var(--foreground)] hover:bg-[rgba(0,0,0,0.04)] dark:hover:bg-[rgba(255,255,255,0.04)] disabled:opacity-50 transition-colors"
      >
        <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>
        {pngLabel}
      </button>
      <span className="text-xs text-[color:var(--muted-foreground)] hidden sm:inline">
        Paste markdown directly into Notion · or drag the PNG into any page
      </span>
    </div>
  );
}

// ── Stat cards ────────────────────────────────────────────────────────────────
function StatCard({ label, value, sub, accent }: { label: string; value: number | string; sub?: string; accent?: string }) {
  return (
    <div className="glass-card p-4 flex flex-col gap-0.5">
      <div className={`text-2xl font-bold tracking-tight tabular-nums ${accent ?? "text-[color:var(--foreground)]"}`}>{value}</div>
      <div className="text-xs font-semibold text-[color:var(--foreground)]">{label}</div>
      {sub && <div className="text-[11px] text-[color:var(--muted-foreground)]">{sub}</div>}
    </div>
  );
}

// ── Phase breakdown row ───────────────────────────────────────────────────────
const PHASE_META = [
  { key: "discovery", label: "Discovery", color: "#818cf8", icon: "🔍" },
  { key: "dev",       label: "Development", color: "#6366f1", icon: "⚙️" },
  { key: "uat",       label: "UAT", color: "#f59e0b", icon: "🧪" },
  { key: "other",     label: "Other active", color: "#71717a", icon: "📌" },
] as const;

function PhaseBreakdown({ by_phase }: { by_phase: WeeklyBundle["by_phase"] }) {
  const total = Object.values(by_phase).reduce((a, b) => a + b, 0);
  return (
    <div className="glass-card p-4">
      <div className="text-[10px] uppercase tracking-widest text-[color:var(--muted-foreground)] mb-3">Active by phase</div>
      <div className="grid grid-cols-4 gap-3">
        {PHASE_META.map(({ key, label, color, icon }) => {
          const count = by_phase[key];
          const pct = total > 0 ? Math.round((count / total) * 100) : 0;
          return (
            <div key={key} className="text-center">
              <div className="text-xl font-bold tabular-nums" style={{ color }}>{count}</div>
              <div className="text-[11px] text-[color:var(--foreground)] font-medium mt-0.5">{icon} {label}</div>
              <div className="text-[10px] text-[color:var(--muted-foreground)]">{pct}% of active</div>
            </div>
          );
        })}
      </div>
      {/* Stacked bar */}
      {total > 0 && (
        <div className="flex rounded-full overflow-hidden h-1.5 mt-3 gap-px">
          {PHASE_META.map(({ key, color }) => {
            const w = total > 0 ? (by_phase[key] / total) * 100 : 0;
            return w > 0 ? (
              <div key={key} style={{ width: `${w}%`, background: color }} />
            ) : null;
          })}
        </div>
      )}
    </div>
  );
}

// ── WoW trend chart ───────────────────────────────────────────────────────────
function WowChart({ data }: { data: WeeklyBundle["wow_trend"] }) {
  const t = useChartTheme();
  const avg = data.length > 0 ? data.reduce((s, d) => s + d.count, 0) / data.length : 0;
  // Short label: "W20" only
  const display = data.map((d) => ({ ...d, shortWeek: d.week.split(" ")[0] }));

  return (
    <ResponsiveContainer width="100%" height={180}>
      <BarChart data={display} margin={{ top: 8, right: 8, left: 0, bottom: 0 }}>
        <CartesianGrid strokeDasharray="3 3" stroke={t.grid} vertical={false} />
        <XAxis dataKey="shortWeek" tick={{ fontSize: 10, fill: t.axis }} tickLine={false} axisLine={false} />
        <YAxis tick={{ fontSize: 10, fill: t.axis }} tickLine={false} axisLine={false} allowDecimals={false} />
        <Tooltip
          contentStyle={t.tooltipStyle}
          labelFormatter={(_, payload) => (payload?.[0]?.payload as { week: string } | undefined)?.week ?? ""}
          formatter={(v) => [v, "Projects delivered"]}
        />
        {avg > 0 && (
          <ReferenceLine y={avg} stroke="#6366f1" strokeDasharray="4 3" strokeOpacity={0.5}
            label={{ value: `avg ${avg.toFixed(1)}`, position: "right", fontSize: 10, fill: "#6366f1" }}
          />
        )}
        <Bar dataKey="count" radius={[3, 3, 0, 0]}>
          {display.map((d, i) => (
            <Cell
              key={i}
              fill={d.count > avg ? "#34d399" : "#818cf8"}
              fillOpacity={d.count === 0 ? 0.25 : 0.9}
            />
          ))}
        </Bar>
      </BarChart>
    </ResponsiveContainer>
  );
}

// ── Project row ───────────────────────────────────────────────────────────────
function ProjectRow({ p, showTtv, badge }: { p: WeeklyProject; showTtv?: boolean; badge?: React.ReactNode }) {
  return (
    <div className="flex items-start gap-3 py-2.5 border-b border-[var(--glass-border)] last:border-0">
      <div className="min-w-0 flex-1">
        <div className="text-sm font-medium text-[color:var(--foreground)] truncate">{p.name}</div>
        <div className="text-xs text-[color:var(--muted-foreground)] mt-0.5 truncate">
          {p.customer_display_name}
          {p.phase && <span className="ml-2 opacity-60">[{p.phase}]</span>}
          {p.tam.length > 0 && <span className="ml-2 opacity-50">· {p.tam[0]}</span>}
        </div>
      </div>
      <div className="flex items-center gap-1.5 shrink-0">
        <HealthPill health={p.health} />
        {badge}
        {showTtv && p.ttv_days !== null && (
          <span className="text-[11px] text-[color:var(--muted-foreground)] tabular-nums">{p.ttv_days}d TTV</span>
        )}
        {p.go_live_date && (
          <span className="text-[11px] text-[color:var(--muted-foreground)] tabular-nums">{fmtDate(p.go_live_date)}</span>
        )}
      </div>
    </div>
  );
}

// ── Section wrapper ───────────────────────────────────────────────────────────
function Section({ title, count, children, countCls }: {
  title: string; count?: number; children: React.ReactNode; countCls?: string;
}) {
  return (
    <section className="glass-card p-5">
      <div className="flex items-center justify-between mb-3">
        <div className="text-sm font-semibold text-[color:var(--foreground)] tracking-tight">{title}</div>
        {count !== undefined && (
          <span className={`text-xs font-bold px-2 py-0.5 rounded-full ${countCls ?? "bg-[var(--glass-border)] text-[color:var(--muted-foreground)]"}`}>
            {count}
          </span>
        )}
      </div>
      {children}
    </section>
  );
}

function Empty({ text }: { text: string }) {
  return <div className="text-xs text-[color:var(--muted-foreground)] italic py-2">{text}</div>;
}

// ── Workload chart ─────────────────────────────────────────────────────────────
const WORKLOAD_COLORS = ["#818cf8","#6366f1","#a78bfa","#8b5cf6","#34d399","#10b981","#60a5fa","#3b82f6"];
function WorkloadChart({ data, sublabel }: { data: Array<{ person: string; active: number }>; sublabel: string }) {
  const t = useChartTheme();
  if (data.length === 0) return <Empty text="No assignments found." />;
  return (
    <>
      <div className="text-[11px] text-[color:var(--muted-foreground)] mb-2">{sublabel}</div>
      <ResponsiveContainer width="100%" height={Math.max(100, data.length * 34)}>
        <BarChart data={data} layout="vertical" margin={{ top: 0, right: 20, left: 0, bottom: 0 }}>
          <CartesianGrid strokeDasharray="3 3" stroke={t.grid} horizontal={false} />
          <XAxis type="number" tick={{ fontSize: 10, fill: t.axis }} tickLine={false} axisLine={false} allowDecimals={false} />
          <YAxis type="category" dataKey="person" tick={{ fontSize: 11, fill: t.axis }} tickLine={false} axisLine={false} width={90} />
          <Tooltip contentStyle={t.tooltipStyle} formatter={(v) => [v, "Active projects"]} />
          <Bar dataKey="active" radius={[0, 3, 3, 0]}>
            {data.map((_, i) => <Cell key={i} fill={WORKLOAD_COLORS[i % WORKLOAD_COLORS.length]} />)}
          </Bar>
        </BarChart>
      </ResponsiveContainer>
    </>
  );
}

// ── In-production stats ────────────────────────────────────────────────────────
function InProdSection({ in_prod, nps }: { in_prod: WeeklyBundle["in_prod"]; nps: WeeklyBundle["nps_this_quarter"] }) {
  const qDelta = in_prod.this_quarter - in_prod.last_quarter;
  return (
    <div className="glass-card p-5">
      <div className="text-sm font-semibold text-[color:var(--foreground)] tracking-tight mb-4">In production</div>
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 mb-4">
        <div className="text-center">
          <div className="text-3xl font-bold text-emerald-600 dark:text-emerald-400 tabular-nums">{in_prod.projects}</div>
          <div className="text-xs text-[color:var(--muted-foreground)] mt-0.5">Total live</div>
        </div>
        <div className="text-center">
          <div className="text-3xl font-bold text-[color:var(--foreground)] tabular-nums">{in_prod.customers}</div>
          <div className="text-xs text-[color:var(--muted-foreground)] mt-0.5">Customers live</div>
        </div>
        <div className="text-center">
          <div className="text-3xl font-bold text-indigo-600 dark:text-indigo-400 tabular-nums">{in_prod.this_quarter}</div>
          <div className="text-xs text-[color:var(--muted-foreground)] mt-0.5">This quarter</div>
        </div>
        <div className="text-center">
          <div className={`text-3xl font-bold tabular-nums flex items-center justify-center gap-1 ${qDelta > 0 ? "text-emerald-600 dark:text-emerald-400" : qDelta < 0 ? "text-red-500" : "text-[color:var(--muted-foreground)]"}`}>
            {qDelta > 0 ? `+${qDelta}` : qDelta}
          </div>
          <div className="text-xs text-[color:var(--muted-foreground)] mt-0.5">vs prev quarter</div>
        </div>
      </div>
      {nps && (
        <div className="border-t border-[var(--glass-border)] pt-4 flex items-center gap-4">
          <div className={`text-2xl font-bold tabular-nums ${nps.average >= 50 ? "text-emerald-600 dark:text-emerald-400" : nps.average >= 0 ? "text-amber-600 dark:text-amber-400" : "text-red-500"}`}>
            {nps.average > 0 ? `+${nps.average}` : nps.average}
          </div>
          <div>
            <div className="text-sm font-medium text-[color:var(--foreground)]">NPS — {nps.quarter}</div>
            <div className="text-xs text-[color:var(--muted-foreground)]">{nps.count} response{nps.count !== 1 ? "s" : ""} this quarter</div>
          </div>
        </div>
      )}
    </div>
  );
}

// ── Main component ─────────────────────────────────────────────────────────────
export function WeeklyReportClient({ bundle }: { bundle: WeeklyBundle }) {
  const { totals } = bundle;
  const reportRef = useRef<HTMLDivElement>(null);

  return (
    <div ref={reportRef} className="space-y-5">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-end justify-between gap-4">
        <div>
          <div className="text-[10px] uppercase tracking-[0.15em] text-[color:var(--muted-foreground)] mb-1">Weekly Delivery Update</div>
          <h1 className="text-3xl font-bold tracking-tight text-[color:var(--foreground)]">{bundle.week_label}</h1>
          <p className="text-sm text-[color:var(--muted-foreground)] mt-1">
            Monday.com · synced {timeAgo(bundle.last_sync)}
          </p>
        </div>
        <ExportButtons bundle={bundle} reportRef={reportRef} />
      </div>

      {/* Row 1 — hero stats */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">
        <StatCard label="Shipped last week" value={totals.shipped_last_week}
          sub={`${totals.delivered_all_time} all time`}
          accent={totals.shipped_last_week > 0 ? "text-emerald-600 dark:text-emerald-400" : undefined} />
        <StatCard label="In flight" value={totals.in_flight} sub="active projects" />
        <StatCard label="In UAT" value={totals.in_uat} sub="ready for sign-off"
          accent={totals.in_uat > 0 ? "text-amber-600 dark:text-amber-400" : undefined} />
        <StatCard label="At risk" value={totals.at_risk} sub="need attention"
          accent={totals.at_risk > 0 ? "text-red-600 dark:text-red-400" : undefined} />
      </div>

      {/* Row 2 — phase breakdown */}
      <PhaseBreakdown by_phase={bundle.by_phase} />

      {/* Row 3 — WoW chart (full width) */}
      <div className="glass-card p-5">
        <div className="flex items-end justify-between mb-1">
          <div>
            <div className="text-sm font-semibold text-[color:var(--foreground)] tracking-tight">Deliveries — week on week</div>
            <div className="text-xs text-[color:var(--muted-foreground)] mt-0.5">Go-lives per week · last 10 weeks · green = above average</div>
          </div>
        </div>
        <WowChart data={bundle.wow_trend} />
      </div>

      {/* Row 4 — Shipped last week + UAT */}
      <div className="grid gap-4 lg:grid-cols-2">
        <Section title="Shipped last week" count={totals.shipped_last_week}
          countCls="bg-emerald-500/12 text-emerald-700 dark:text-emerald-400">
          {bundle.shipped_last_week.length === 0
            ? <Empty text="No projects went live last week." />
            : bundle.shipped_last_week.map((p) => <ProjectRow key={p.monday_item_id} p={p} showTtv />)}
        </Section>

        <Section title="In UAT — ready for sign-off" count={totals.in_uat}
          countCls="bg-amber-500/12 text-amber-700 dark:text-amber-400">
          {bundle.in_uat.length === 0
            ? <Empty text="No projects currently in UAT." />
            : bundle.in_uat.map((p) => (
                <ProjectRow key={p.monday_item_id} p={p}
                  badge={<span className="text-[10px] px-1.5 py-0.5 rounded border border-amber-500/25 bg-amber-500/10 text-amber-700 dark:text-amber-400 font-medium">UAT</span>}
                />
              ))}
        </Section>
      </div>

      {/* Row 5 — At risk + In flight */}
      <div className="grid gap-4 lg:grid-cols-3">
        <Section title="At risk" count={totals.at_risk}
          countCls={totals.at_risk > 0 ? "bg-red-500/12 text-red-700 dark:text-red-400" : undefined}>
          {bundle.at_risk.length === 0
            ? <div className="flex items-center gap-2 py-2 text-sm text-emerald-700 dark:text-emerald-400"><span>✓</span> All clear.</div>
            : bundle.at_risk.map((p) => (
                <div key={p.monday_item_id} className="py-2.5 border-b border-[var(--glass-border)] last:border-0">
                  <div className="flex items-start justify-between gap-2">
                    <div className="min-w-0 flex-1">
                      <div className="text-sm font-medium text-[color:var(--foreground)] truncate">{p.name}</div>
                      <div className="text-xs text-[color:var(--muted-foreground)]">{p.customer_display_name}</div>
                    </div>
                    <HealthPill health={p.health} />
                  </div>
                  {p.latest_update && (
                    <div className="text-xs text-[color:var(--muted-foreground)] mt-1.5 line-clamp-2 italic">{p.latest_update}</div>
                  )}
                </div>
              ))}
        </Section>

        <div className="lg:col-span-2">
          <Section title="In flight" count={totals.in_flight}>
            {bundle.in_flight.length === 0
              ? <Empty text="No active projects." />
              : <div className="max-h-80 overflow-y-auto">
                  {bundle.in_flight.map((p) => <ProjectRow key={p.monday_item_id} p={p} />)}
                </div>}
          </Section>
        </div>
      </div>

      {/* Row 6 — In production stats */}
      <InProdSection in_prod={bundle.in_prod} nps={bundle.nps_this_quarter} />

      {/* Row 7 — Team workload (moved to bottom) */}
      <div className="glass-card p-5">
        <div className="text-sm font-semibold text-[color:var(--foreground)] tracking-tight mb-4">Team workload — active projects</div>
        <div className="grid gap-6 lg:grid-cols-2">
          <WorkloadChart data={bundle.workload_tam} sublabel="TAM / CSM" />
          <WorkloadChart data={bundle.workload_dev} sublabel="Engineering / SE" />
        </div>
      </div>

      {/* Footer */}
      <div className="text-[11px] text-[color:var(--muted-foreground)] text-center pt-1">
        Generated by DeliveryOps · data from Monday.com · {new Date(bundle.generated_at).toLocaleString("en-US", { dateStyle: "medium", timeStyle: "short" })}
      </div>
    </div>
  );
}
