-- One-time seed of migration_processes from the V2 Migration List (Working Sheet, 75 rows).
-- Generated from the spreadsheet: status normalized to migration_stage, Linear IDs parsed
-- from cell text + hyperlinks, went_live_at pre-stamped on already-live rows so the Slack
-- notifier does not retro-fire, customer_key left null for a later matching pass.

insert into migration_processes
  (account, customer_key, process_name, process_status, platform, migration_stage, is_blocked, priority, fde_owner, engg_owner, date_parity_complete, date_customer_handover, date_customer_validation, go_live_date, completion_pct, effort_required, went_live_at, active_usage, customer_notified, customer_contact, blockers, notes, feature_delta, linear_ticket_ids, v2_workspace_url, arr, company_size, source_phase, source_board)
values
  ('Airborne', NULL, 'Airborne - Invoice Processing', 'Live', 'V1', 'not_required', false, NULL, 'Ayush', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', NULL, 16500.0, '~$40M', 'M5 - Exception Handling', 'FY-2025'),
  ('Airborne', NULL, 'Airborne - RAG process', 'In Development', 'Custom Solution', 'not_required', false, NULL, 'Ayush Ghosh', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NA', '{}', NULL, NULL, NULL, 'M2 - Development', 'Projects (active)'),
  ('Bradley & Beams', NULL, 'Bradley & Beams - Engagement Letter Flow - v2 Migration', 'Live', 'V2', 'v2_native', false, NULL, 'Rishabh Malhotra', NULL, NULL, NULL, NULL, '2026-03-19', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', NULL, NULL, NULL, 'Migrated to v2', 'FY-2026'),
  ('Bradley & Beams', NULL, 'Bradley & Beams - Tax File Renaming', 'Live', 'V2', 'v2_native', false, NULL, 'Rishabh Malhotra', NULL, NULL, NULL, NULL, '2026-02-25', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', NULL, NULL, NULL, 'Customer Handling exceptions', 'FY-2026'),
  ('Bradley & Beams', NULL, 'Bradley & Beams - Tax Reconciliation Yardi', 'Live', 'V1', 'not_required', false, 'Low', 'Rishabh Malhotra', NULL, NULL, NULL, NULL, '2025-10-31', NULL, '1 week', NULL, NULL, NULL, NULL, NULL, NULL, 'No Blockers', '{}', NULL, 16000.0, '~$10M', 'M5 - Exception Handling', 'FY-2025'),
  ('Bradley & Beams', NULL, 'Bradley & Beams - Tax Recon Vantaca and Random Flow', 'Live', 'V1', 'not_required', false, 'Low', 'Rishabh Malhotra', NULL, NULL, NULL, NULL, '2026-01-22', NULL, '2 weeks', NULL, NULL, NULL, NULL, NULL, NULL, 'No Blockers', '{}', NULL, 16000.0, '~$10M', 'M5 - Exception Handling', 'FY-2025'),
  ('Bradley & Beams', NULL, 'Bradley & Beams - Engagement Letters', 'Live', 'V1', 'not_required', false, 'Low', 'Rishabh Malhotra', NULL, NULL, NULL, NULL, '2025-10-31', NULL, '4 days', NULL, NULL, NULL, NULL, NULL, NULL, 'No Blockers', '{}', NULL, 16000.0, '~$10M', 'M5 - Exception Handling', 'FY-2025'),
  ('Century', NULL, 'Century - BOL', 'Live', 'V1', 'parity_testing', true, 'High', 'Paige Gill', NULL, '2026-07-24', NULL, NULL, '2023-12-30', NULL, '2 weeks', NULL, NULL, 'No', NULL, 'Collection with Fuzzy matching is required', NULL, 'Collection with Fuzzy matching is required', '{"ENG-4302"}', NULL, 264000.0, '~$120M', 'Customer Handling exceptions', 'FY-2023'),
  ('Century', NULL, 'Century - Carrier Booking', 'Live', 'V1', 'parity_testing', true, 'High', 'Paige Gill', NULL, '2026-07-24', NULL, NULL, '2024-12-10', NULL, '3 weeks', NULL, NULL, 'No', NULL, 'Collection with Fuzzy matching is required', NULL, 'Collection with Fuzzy matching is required', '{"ENG-4302"}', NULL, 264000.0, '~$120M', 'Customer Handling exceptions', 'FY-2025'),
  ('Ciena', NULL, 'Ciena - PO', 'Live', 'V1', 'customer_validation', true, 'High', 'Rishabh Malhotra', NULL, '2026-06-25', '2026-07-20', NULL, '2025-05-30', 0.6, '3 weeks', NULL, '1850 per month', 'Yes', 'Suresh', 'IDP Experience, Prompt Management - Visibility into what business rules were used for which customer, Scalability to other customers since Quill regresses and makes a lot of mistakes while updating IDP prompts', NULL, 'Lack of prompt management for multiple documents, lack of visibility towards prompts being used by SPy. Waiting for Assets/Collections to see how that experience changes before sharing anything with customer', '{"ENG-3827"}', NULL, 25000.0, '~$4.4B', 'Support', 'FY-2025'),
  ('Conectiv', NULL, 'Conectiv POV', 'In Development', 'V1', 'in_development', true, 'High', 'Ayush', 'Kalpesh', '2026-07-31', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'No', 'Dmitry and Christine', 'Parallel processing due to large file', NULL, '- Can''t upload files more than 50 MB
- Using collection as File storage????
- Excel file processing with more than 1 million rows
- Parallel runs
- Sub procedure calls
- BDK Excel pod memory upgrade
- bishop file intake size upgrade', '{"ENG-4375","ENG-4429","KOG-11844","KOG-11845","KOG-11887","KOG-11888","KOG-11890","KOG-11894"}', NULL, 65000.0, '~$2.1B', 'M3 - Testing/UAT', 'Projects (active)'),
  ('ET Global', NULL, 'ET Global POV', 'Churned', 'V1', 'not_required', false, NULL, 'NA', NULL, NULL, NULL, NULL, '2026-01-08', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', NULL, 95000.0, '~$80M', 'Waiting for Customer', 'FY-2025'),
  ('Halemeyer', NULL, 'Halemeyer - Bill Pay Enhancements', 'To be Dropped', 'V1', 'not_required', false, 'Low', 'Karthik N', NULL, NULL, NULL, NULL, '2026-04-27', NULL, '1 week', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', NULL, 4000.0, '~$5M', 'Customer Handling exceptions', 'FY-2026'),
  ('Halemeyer', NULL, 'Halemeyer - Bill Pay', 'To be Dropped', 'V1', 'not_required', false, 'Low', 'Karthik N', NULL, NULL, NULL, NULL, '2025-09-10', NULL, '1 week', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', NULL, 4000.0, '~$5M', 'Support', 'FY-2025'),
  ('Hwy Haul', NULL, 'Hwy Haul - RFP Requests', 'Live', 'V1', 'not_required', false, NULL, 'NA', NULL, NULL, NULL, NULL, '2025-06-19', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', NULL, 500.0, '~$20M', 'M5 - Exception Handling', 'FY-2025'),
  ('iHeartRadio', NULL, 'Wipro DOP - iHeartRadio - Premiere Programming Affidavits', 'Live', 'V1', 'parity_testing', false, 'Medium', 'Ayush', NULL, '2026-07-17', '2026-07-24', NULL, '2025-09-22', NULL, '2-3 weeks', NULL, NULL, 'No', 'Akshay Saini, Giby George - Wipro', NULL, NULL, '- Parallel runs, sub processes', '{"OC-1395"}', NULL, 120000.0, '~$3.8B', 'Support', 'FY-2025'),
  ('JBI', NULL, 'JBI - Merch PO intake', 'Live', 'V1', 'customer_validation', false, 'High', 'Rishabh Malhotra', NULL, '2026-06-26', '2026-07-20', '2026-07-25', '2024-08-17', NULL, '1 week', NULL, '350 per month', 'Yes', 'Donna', NULL, NULL, NULL, '{"INT-1476"}', NULL, 384335.0, '~$45M', 'M5 - Exception Handling', 'FY-2024'),
  ('JBI', NULL, 'JBI - QSR Quote Generator', 'Live', 'V1', 'customer_validation', false, 'High', 'Rishabh Malhotra', NULL, '2026-06-23', '2026-07-07', '2026-07-22', '2025-04-30', NULL, '1 week', NULL, '10 per month', 'Yes', 'Jorge', NULL, 'Handed over to users for UAT despite the linear ticket being open as user can verify the output while issue is being worked on', 'Not stable, a lot of IDP, Excel stream timeout issues. Will start UAT with customer this week though', '{"KOG-11824"}', NULL, 384335.0, '~$45M', 'M5 - Exception Handling', 'FY-2025'),
  ('JBI', NULL, 'JBI - SBUX Quote Generator', 'Live', 'V1', 'live_on_v2', false, 'High', 'Rishabh Malhotra', NULL, '2026-06-23', NULL, NULL, '2024-07-27', NULL, '2 weeks', '2024-07-27', 'NA', 'Yes', 'Jorge', NULL, NULL, NULL, '{"KOG-11815","KOG-11824"}', NULL, 384335.0, '~$45M', 'M5 - Exception Handling', 'FY-2024'),
  ('JBI', NULL, 'JBI - Design Meeting Preparation', 'Live', 'V1', 'engg_pending', false, 'High', 'Rishabh Malhotra', NULL, '2026-06-24', '2026-07-07', NULL, '2026-01-22', NULL, '3 days', NULL, '10 per month', 'Yes', 'Jorge', NULL, NULL, NULL, '{"INT-1509","KOG-11859"}', NULL, 384335.0, '~$45M', 'M5 - Exception Handling', 'FY-2025'),
  ('JBI', NULL, 'JBI - Project initiation request', 'Retired', 'V1', 'not_required', false, NULL, 'Rishabh Malhotra', NULL, NULL, NULL, NULL, '2024-10-06', NULL, 'NA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', NULL, NULL, NULL, 'M5 - Exception Handling', 'FY-2024'),
  ('JBI', NULL, 'JBI - Time Cards', 'Live', 'V2', 'v2_native', false, 'High', 'Rishabh Malhotra', NULL, NULL, NULL, NULL, '2026-05-14', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', NULL, NULL, NULL, 'M5 - Exception Handling', 'FY-2026'),
  ('JBI', NULL, 'JBI - Managing Onsite Date Change', 'Live', 'V1', 'parity_testing', false, 'High', 'Arushi', NULL, '2026-07-22', '2026-07-22', '2026-07-21', '2026-02-18', NULL, '1 week', NULL, NULL, 'Yes', 'Ken', NULL, NULL, 'Sub-process call', '{"OC-1427"}', NULL, 384335.0, '~$45M', 'M5 - Exception Handling', 'FY-2026'),
  ('JBI', NULL, 'JBI - Project Initiation Request v2', 'Live', 'V1', 'live_on_v2', false, 'High', 'Rishabh Malhotra', NULL, '2026-06-24', '2026-07-13', '2026-07-20', '2025-05-15', NULL, '3 days', '2025-05-15', '10 per month', 'Yes', 'Frank', NULL, NULL, NULL, '{}', NULL, 384335.0, '~$45M', 'M5 - Exception Handling', 'FY-2025'),
  ('JBI', NULL, 'JBI - AP Invoice Processing', 'Live', 'V1', 'parity_testing', false, 'High', 'Rishabh Malhotra', NULL, '2026-06-26', NULL, NULL, '2024-07-27', NULL, '8 days', NULL, '350 per month', 'Yes', 'Nancy', NULL, NULL, NULL, '{"KOG-11810"}', NULL, 384335.0, '~$45M', 'Customer Handling exceptions', 'FY-2023'),
  ('Kort Payments', NULL, 'Kort Payments - 7 Docs', 'In Development', 'V1', 'engg_pending', true, 'High', 'Paige Gill', NULL, '2026-07-03', NULL, NULL, NULL, NULL, '2 weeks', NULL, NULL, 'Yes', 'Adam', 'Browser Automation - IP Whitelisting', NULL, NULL, '{}', NULL, 140800.0, '~$25M', 'M3 - Testing/UAT', 'Projects (active)'),
  ('Kort Payments', NULL, 'Kort Payments - Sales Support Field Transfer', 'In Development', 'V1', 'engg_pending', true, 'High', 'Paige Gill', NULL, '2026-07-03', NULL, NULL, NULL, NULL, '2 weeks', NULL, NULL, 'Yes', 'Adam', 'Browser Automation - IP Whitelisting', NULL, NULL, '{}', NULL, 140800.0, '~$25M', 'M3 - Testing/UAT', 'Projects (active)'),
  ('Kort Payments', NULL, 'Kort Payments - Account Closures', 'In Development', 'V1', 'engg_pending', true, 'High', 'Karthik N', 'Sasha', '2026-07-03', NULL, NULL, NULL, NULL, '2 weeks', NULL, NULL, 'Yes', 'Adam', 'Browser Automation - IP Whitelisting', NULL, '- Browser automation is brittle and painfully slow as experienced with Century''s new project
- Browser automation with Quill 2
- Browser automation (add Linear ticket - currently Sasha is working on this - add more details on the roadblocks - add timeline)
- IDP', '{}', NULL, 140800.0, '~$25M', 'M3 - Testing/UAT', 'Projects (active)'),
  ('Kort Payments', NULL, 'Kort Payments - Dash Deployment', 'In Development', 'V1', 'engg_pending', true, 'High', 'Karthik N', 'Sasha', '2026-07-03', NULL, NULL, NULL, NULL, '2 weeks', NULL, NULL, 'Yes', 'Adam', 'Browser Automation - IP Whitelisting', NULL, '- Browser automation
- IDP', '{}', NULL, 140800.0, '~$25M', 'M3 - Testing/UAT', 'Projects (active)'),
  ('Mitie', NULL, 'Wipro DOP - Mitie - Invoice Registration Log', 'Live', 'V1', 'not_required', false, 'Medium', 'Rishabh Malhotra', 'Sid', '2026-07-03', NULL, NULL, '2025-11-07', NULL, '3 weeks', NULL, NULL, 'No', 'Prudvi', NULL, NULL, NULL, '{"OC-1361","OC-1362"}', NULL, 420000.0, '~£4.5B', 'Support', 'FY-2025'),
  ('Mitie', NULL, 'Wipro DOP - Mitie - PCard', 'Live', 'V1', 'engg_pending', false, 'Medium', 'Rishabh Malhotra', 'Sid', '2026-07-03', NULL, NULL, '2025-01-31', NULL, '3 weeks', NULL, NULL, 'No', 'Prudvi', NULL, NULL, 'Do we have a UK instance for v2? Otherwise where should we migrate Mitie processes?

Using app.us-1 for now for testing', '{"KOG-11842","OC-1357","OC-1359","OC-1360"}', NULL, 420000.0, '~£4.5B', 'Support', 'FY-2025'),
  ('Mitie', NULL, 'Wipro DOP - Mitie - WIP', 'Live', 'V1', 'not_required', false, 'Medium', 'Rishabh Malhotra', 'Sid', '2026-07-03', NULL, NULL, '2025-11-21', NULL, '3 weeks', NULL, NULL, 'No', 'Prudvi', NULL, NULL, NULL, '{"OC-1358"}', NULL, 420000.0, '~£4.5B', 'Support', 'FY-2025'),
  ('Norco', NULL, 'Norco - Packslip Sorting', 'Live', 'V2', 'live_on_v2', false, 'High', 'Karthik N', NULL, '2026-06-12', NULL, NULL, '2026-01-07', NULL, 'N/A', '2026-01-07', NULL, 'Yes', 'Stephanie', NULL, NULL, NULL, '{}', NULL, NULL, NULL, 'M5 - Exception Handling', 'FY-2026'),
  ('Norco', NULL, 'Norco - Personal Koncierge', 'Discovery', 'Custom Solution', 'not_required', false, NULL, 'NA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', NULL, NULL, NULL, 'Waiting for Customer', 'Projects (active)'),
  ('Norco', NULL, 'Norco - HR Voicemail', 'Live', 'V1', 'not_required', false, 'High', 'Karthik N', NULL, NULL, NULL, NULL, '2024-06-29', NULL, '1 week', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', NULL, NULL, NULL, 'M5 - Exception Handling', 'FY-2023'),
  ('Norco', NULL, 'Norco - AR', 'Live', 'V1', 'in_development', false, 'High', 'Paige Gill', NULL, '2026-07-28', NULL, NULL, '2023-04-21', NULL, '2 weeks', NULL, NULL, 'No', NULL, NULL, NULL, NULL, '{}', NULL, 639000.0, '~$150M', 'M5 - Exception Handling', 'FY-2023'),
  ('Norco', NULL, 'Norco - Parts Reconciliation', 'Live', 'V1', 'customer_validation', false, 'High', 'Karthik N', NULL, '2026-06-26', NULL, NULL, '2024-04-19', NULL, '2 weeks', NULL, NULL, 'Yes', 'Stephanie', NULL, NULL, NULL, '{}', NULL, 639000.0, '~$150M', 'M5 - Exception Handling', 'FY-2024'),
  ('Norco', NULL, 'Norco - Safety Culture Audit', 'Live', 'V1', 'in_development', false, 'High', 'Karthik N', NULL, '2026-07-28', NULL, NULL, '2024-09-17', NULL, '2 weeks', NULL, NULL, 'No', NULL, NULL, NULL, NULL, '{}', NULL, 639000.0, '~$150M', 'M5 - Exception Handling', 'FY-2024'),
  ('Norco', NULL, 'Norco - Solar Winds', 'Live', 'V1', 'parity_testing', false, 'High', 'Karthik N', NULL, '2026-07-24', NULL, NULL, NULL, NULL, '2 weeks', NULL, NULL, 'No', NULL, NULL, NULL, NULL, '{}', NULL, 639000.0, '~$150M', 'M5 - Exception Handling', 'FY-2025'),
  ('Ozark River', NULL, 'Ozark River - Amazon verification', 'To be Dropped', 'V1', 'not_required', false, 'High', 'Arushi', NULL, NULL, NULL, NULL, '2026-02-03', NULL, '1 week', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', NULL, 22500.0, '~$12M', 'M5 - Exception Handling', 'FY-2026'),
  ('Ozark River', NULL, 'Ozark River - Cash Flow Reconciliation', 'To be Dropped', 'V1', 'not_required', false, 'High', 'Arushi', NULL, NULL, NULL, NULL, '2025-10-07', NULL, '1 week', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', NULL, 22500.0, '~$12M', 'M5 - Exception Handling', 'FY-2025'),
  ('Pepsi', NULL, 'Pepsi - ServiceNow Ticketing', 'Live', 'V1', 'customer_validation', false, 'High', 'Ayush', 'Rushil', '2026-07-03', '2026-07-10', NULL, '2025-01-24', NULL, NULL, NULL, NULL, 'No', 'Patrycja', NULL, NULL, 'Quill2 integration with Collections on Prod - Pending', '{"KOG-11854","KOG-11855"}', NULL, 31682.0, '~$92B', 'Customer Handling exceptions', 'FY-2024'),
  ('Pepsi', NULL, 'Pepsi - Fuzzy Matching', 'Live', 'V1', 'not_required', false, NULL, 'Ayush', NULL, '2026-07-03', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'No', NULL, NULL, NULL, NULL, '{}', NULL, NULL, NULL, NULL, NULL),
  ('Plunkett', NULL, 'Plunkett - Create Customer Payments', 'Live', 'V1', 'customer_validation', false, 'High', 'Arushi', 'Sasha', '2026-06-19', '2026-06-23', '2026-07-21', '2025-11-11', NULL, '1 week', NULL, NULL, 'Yes', 'Paul & Tricia', NULL, NULL, NULL, '{}', NULL, 6000.0, '~$80M', 'M5 - Exception Handling', 'FY-2025'),
  ('Plunkett', NULL, 'Plunkett - Customer Claim RA', 'Live', 'V1', 'live_on_v2', false, 'High', 'Arushi', 'Sasha', '2026-06-19', '2026-06-23', '2026-07-21', '2025-11-11', NULL, '1 week', '2025-11-11', NULL, 'Yes', 'Paul & Tricia', NULL, NULL, NULL, '{}', NULL, 6000.0, '~$80M', 'M5 - Exception Handling', 'FY-2025'),
  ('Plunkett', NULL, 'Plunkett - Sales Order Creation', 'Live', 'V1', 'live_on_v2', false, 'High', 'Arushi', 'Sasha', '2026-06-19', '2026-06-23', '2026-07-21', '2026-01-27', NULL, '1 week', '2026-01-27', NULL, 'Yes', 'Paul & Tricia', NULL, NULL, NULL, '{}', NULL, 6000.0, '~$80M', 'M5 - Exception Handling', 'FY-2025'),
  ('Plunkett', NULL, 'Plunkett - Vendor Bill Non PO', 'Live', 'V1', 'customer_validation', false, 'High', 'Arushi', 'Sasha', '2026-07-06', '2026-07-07', '2026-08-07', '2026-01-27', NULL, '1 week', NULL, NULL, 'Yes', 'Paul & Tricia', NULL, NULL, NULL, '{}', NULL, 6000.0, '~$80M', 'M5 - Exception Handling', 'FY-2025'),
  ('Salesbricks', NULL, 'Salesbricks - Process', 'To be Dropped', 'V1', 'not_required', false, 'Medium', 'Karthik N', NULL, NULL, NULL, NULL, '2026-01-05', NULL, '1 week', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', NULL, 24000.0, '~$4M', 'M5 - Exception Handling', 'FY-2025'),
  ('Scan Health', NULL, 'Indium - Scan Health - Enrollment Form Digitization', 'Live', 'V1', 'customer_validation', false, 'High', 'Ayush', 'Mohsin / Vihang', '2026-07-01', NULL, '2026-07-31', '2026-03-19', NULL, '2 weeks', NULL, NULL, 'Yes', 'Amber / Aritra', NULL, NULL, '- IDP extraction for 400 fields
- run inconsistencies (Vihang is engaged)
- Parallel runs
- Sub procedure calls', '{"KOG-11762","KOG-11786"}', NULL, 84000.0, '~$4.8B', 'Enhancement', 'FY-2026'),
  ('Scan Health', NULL, 'Scan Health - Report', 'Live', 'V1', 'not_required', false, 'High', 'Ayush', 'Mohsin / Vihang', '2026-06-24', NULL, '2026-07-31', '2025-10-22', NULL, '2 weeks', NULL, NULL, 'Yes', 'Amber / Aritra', NULL, NULL, NULL, '{}', NULL, 84000.0, '~$4.8B', 'Support', 'FY-2025'),
  ('SSD/SKP', NULL, 'SSD', 'Live', 'V1', 'not_required', false, NULL, 'NA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', NULL, NULL, NULL, 'M5 - Exception Handling', 'FY-2024'),
  ('TTX', NULL, 'TTX - Lease Invoicing', 'Live', 'V1', 'live_on_v2', false, 'High', 'Paige Gill', NULL, '2026-06-16', NULL, NULL, '2024-12-09', NULL, 'Completed', '2024-12-09', NULL, 'Yes', 'James', NULL, NULL, NULL, '{}', NULL, 20000.0, '~$1.8B', 'Customer Handling exceptions', 'FY-2024'),
  ('TTX', NULL, 'TTX - AP Invoicing', 'Live', 'V1', 'customer_validation', false, 'High', 'Paige Gill', NULL, '2026-06-25', '2026-06-25', '2026-07-31', '2025-05-20', NULL, '2 weeks', NULL, NULL, 'Yes', 'James', NULL, NULL, NULL, '{}', NULL, 20000.0, '~$1.8B', 'Customer Handling exceptions', 'FY-2025'),
  ('TTX', NULL, 'TTX - Brake Inspection AR Invoices', 'Live', 'V1', 'customer_validation', false, 'High', 'Paige Gill', NULL, '2026-06-23', '2026-06-24', '2026-07-31', '2025-04-30', NULL, '1 week', NULL, NULL, 'Yes', 'James', NULL, NULL, NULL, '{}', NULL, 20000.0, '~$1.8B', 'Customer Handling exceptions', 'FY-2025'),
  ('TTX', NULL, 'TTX - COA', 'Live', 'V1', 'live_on_v2', false, 'High', 'Paige Gill', NULL, '2026-06-25', '2026-06-25', '2026-07-17', '2025-02-07', NULL, '1 week', '2025-02-07', NULL, 'Yes', 'James', NULL, NULL, NULL, '{"ENG-4201"}', NULL, 20000.0, '~$1.8B', 'M5 - Exception Handling', 'FY-2025'),
  ('TTX', NULL, 'TTX - Goods Receipt', 'Live', 'V1', 'customer_validation', false, 'High', 'Paige Gill', NULL, '2026-06-25', '2026-06-25', '2026-07-17', '2025-09-26', NULL, 'Completed', NULL, NULL, 'Yes', 'James', NULL, NULL, NULL, '{}', NULL, 20000.0, '~$1.8B', 'Customer Handling exceptions', 'FY-2025'),
  ('Union', NULL, 'Union Commercial', 'Live', 'V1', 'not_required', false, NULL, 'Paige Gill', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', NULL, 7000.0, '~$40M', 'M5 - Exception Handling', 'FY-2024'),
  ('Wipro FSS', NULL, 'Wipro Indirect Tax Computations Enhancement', 'Live', 'V1', 'not_required', false, 'High', 'Karthik N', 'Sid', NULL, NULL, NULL, '2026-03-27', NULL, '1 week', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', NULL, 110000.0, '$11B', 'Enhancement', 'FY-2026'),
  ('Wipro FSS', NULL, 'Wipro Vouching Process Enhancements', 'Live', 'V1', 'not_required', false, 'High', 'Karthik N', 'Sid', NULL, NULL, NULL, '2026-04-16', NULL, '1 week', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', NULL, 110000.0, '$11B', 'Enhancement', 'FY-2026'),
  ('Wipro FSS', NULL, 'Wipro FSS - Indirect Tax Computations', 'Live', 'V1', 'parity_testing', false, 'High', 'Karthik N', NULL, '2026-06-23', NULL, NULL, '2026-01-27', NULL, '1 week', NULL, NULL, 'Yes', NULL, NULL, NULL, 'Processing Large files causes the thread to block and throw errors.

Plus enhacement request', '{"ENG-4215","OC-1349","OC-1366","OC-1413"}', NULL, 110000.0, '$11B', 'M5 - Exception Handling', 'FY-2025'),
  ('Wipro FSS', NULL, 'Wipro FSS - WTSL', 'Live', 'V1', 'not_required', false, 'High', 'Karthik N', 'Sid', NULL, NULL, NULL, '2024-11-15', NULL, '1 week', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', NULL, 110000.0, '$11B', 'M5 - Exception Handling', 'FY-2024'),
  ('Wipro FSS', NULL, 'Wipro FSS - VHD Enhancements', 'In Development', 'V1', 'not_required', false, 'High', 'Karthik N', 'Sid', NULL, NULL, NULL, NULL, NULL, '2 weeks', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', NULL, 110000.0, '$11B', 'M2 - Development', 'Projects (active)'),
  ('Wipro FSS', NULL, 'Wipro FSS - Collection Accounting', 'Live', 'V1', 'in_development', false, 'High', 'Karthik N', NULL, '2026-07-13', '2026-07-22', NULL, '2023-12-22', NULL, '2 weeks', NULL, NULL, 'No', NULL, NULL, 'Waiting on confirmation from customer', 'Python code migration?', '{"OC-1433"}', NULL, 110000.0, '$11B', 'M5 - Exception Handling', 'FY-2023'),
  ('Wipro FSS', NULL, 'Wipro FSS - GP Vendor Query Response', 'Live', 'V1', 'parity_testing', false, 'High', 'Arushi', NULL, '2026-07-09', '2026-07-22', '2026-07-31', '2025-09-08', NULL, '2 weeks', NULL, NULL, 'No', NULL, NULL, NULL, NULL, '{}', NULL, 110000.0, '$11B', 'Support', 'FY-2025'),
  ('Wipro FSS', NULL, 'Wipro FSS - Ariba CA Invoice Validation', 'Live', 'V1', 'parity_testing', false, 'High', 'Karthik N', NULL, '2026-06-23', '2026-07-22', NULL, '2024-11-15', NULL, '3 days', NULL, NULL, 'No', NULL, NULL, NULL, '- Parallel runs (IDP for multiple PDF ~100)', '{}', NULL, 110000.0, '$11B', 'M5 - Exception Handling', 'FY-2024'),
  ('Wipro FSS', NULL, 'Wipro FSS - Bank Charges Invoice Extraction', 'Live', 'V1', 'parity_testing', false, 'High', 'Karthik N', NULL, '2026-06-23', '2026-07-22', NULL, '2025-03-14', NULL, '3 weeks', NULL, NULL, 'No', NULL, NULL, NULL, '- Parallel runs (IDP for multiple PDF ~100)', '{}', NULL, 110000.0, '$11B', 'M5 - Exception Handling', 'FY-2025'),
  ('Wipro FSS', NULL, 'Wipro FSS - Claim Invoice Extraction', 'Live', 'V1', 'parity_testing', false, 'High', 'Karthik N', NULL, '2026-06-23', '2026-07-22', NULL, '2025-03-14', NULL, '3 weeks', NULL, NULL, 'No', NULL, NULL, NULL, '- Parallel runs (IDP for multiple PDF ~100)', '{}', NULL, 110000.0, '$11B', 'M5 - Exception Handling', 'FY-2025'),
  ('Wipro FSS', NULL, 'Wipro FSS - RCM Vouching', 'Live', 'V1', 'parity_testing', false, 'High', 'Karthik N', NULL, '2026-06-23', '2026-07-22', NULL, '2025-02-26', NULL, '4 days', NULL, NULL, 'No', NULL, NULL, NULL, '- Parallel runs (IDP for multiple PDF ~100)', '{}', NULL, 110000.0, '$11B', 'M5 - Exception Handling', 'FY-2025'),
  ('Wipro FSS', NULL, 'Wipro FSS - Bank Confirmation Extraction', 'Live', 'V1', 'parity_testing', false, 'High', 'Karthik N', NULL, '2026-06-23', '2026-07-22', NULL, '2025-05-30', NULL, '2 weeks', NULL, NULL, 'No', NULL, NULL, NULL, '- Parallel runs (IDP for multiple PDF ~100)', '{}', NULL, 110000.0, '$11B', 'M5 - Exception Handling', 'FY-2025'),
  ('Wipro FSS', NULL, 'Wipro FSS - GBL Finance Zcop PPC Cost Tracking', 'Live', 'V1', 'not_required', false, 'High', 'Karthik N', 'Sid', NULL, NULL, NULL, '2025-05-30', NULL, '2 weeks', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', NULL, 110000.0, '$11B', 'M5 - Exception Handling', 'FY-2025'),
  ('Wipro FSS', NULL, 'Wipro LCC Enhancements', 'Live', 'V1', 'not_required', false, 'High', 'Karthik N', 'Sid', NULL, NULL, NULL, '2026-05-11', NULL, '3 days', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', NULL, 110000.0, '$11B', 'M5 - Exception Handling', 'FY-2026'),
  ('Wipro FSS', NULL, 'Wipro FSS - LCC', 'Live', 'V1', 'parity_testing', false, 'High', 'Karthik N', NULL, '2026-06-26', '2026-07-22', NULL, '2024-11-15', NULL, '3 days', NULL, NULL, 'No', NULL, NULL, NULL, '- Parallel runs (IDP for multiple PDF ~300)', '{"OC-1365"}', NULL, 110000.0, '$11B', 'M5 - Exception Handling', 'FY-2024'),
  ('Wipro FSS', NULL, 'Wipro FSS - BRS', 'Live', 'V1', 'in_development', false, 'High', 'Karthik N', NULL, '2026-07-13', '2026-07-22', NULL, '2025-03-14', NULL, '3 weeks', NULL, NULL, 'No', NULL, NULL, 'This will be a fresh build most probably', NULL, '{"OC-1364"}', NULL, 110000.0, '$11B', 'M5 - Exception Handling', 'FY-2025'),
  ('Wipro FSS', NULL, 'Wipro FSS - DSPF SEZ', 'Live', 'V1', 'parity_testing', false, 'High', 'Arushi', NULL, '2026-07-09', '2026-07-22', '2026-07-31', '2025-03-14', NULL, '3 weeks', NULL, NULL, 'No', NULL, NULL, NULL, 'need parallel IDP porcessing in prod', '{}', NULL, 110000.0, '$11B', 'M5 - Exception Handling', 'FY-2025'),
  ('Wipro FSS', NULL, 'Wipro FSS - Tax Vouching Process', 'Live', 'V1', 'parity_testing', false, 'High', 'Karthik N', NULL, '2026-07-07', '2026-07-22', NULL, '2025-02-26', NULL, '4 days', NULL, NULL, 'No', NULL, NULL, NULL, NULL, '{}', NULL, 110000.0, '$11B', 'M5 - Exception Handling', 'FY-2025');
